blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/timbenniks/tripsmith-app/discussions
    about: Ask questions or discuss ideas that aren't quite ready for issues yet
